# pull the official base image
FROM node:18

# set working direction
EXPOSE 80
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

# add app
COPY . .
RUN npm install
RUN npm install -g serve
RUN npm run build

# start app
CMD ["serve", "-l", "80",  "-s", "dist"]