version: "3.8"

services:
    backend:
        image: supakornhobby.azurecr.io/web-article-test-backend:latest
        ports:
            - "8000:8000"
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: pgdb
            DB_DATABASE: web-article
            NODE_ENV: development
            PORT: 8000
            JWT_SECRET: 380efd7b98c6f423e2736c4f
        depends_on:
            - db

    frontend:
        image: supakornhobby.azurecr.io/web-article-test-frontend:latest
        ports:
            - "3000:3000"
        environment:
            REACT_APP_ENV: DEVELOPMENT
            REACT_APP_API: http://backend:8000
            REACT_APP_PORT: 3000

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: web-article
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pgdb
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
